from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data" / "raw_pdfs"
CHROMA_DIR = BASE_DIR / "data" / "chroma_db"
EVAL_DIR = BASE_DIR / "eval"

CHUNK_SIZE = 400
CHUNK_OVERLAP = 100
MIN_CHUNK_SIZE = 80

EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

LLM_MODEL = "google/flan-t5-small"
LLM_MAX_TOKENS = 350
LLM_TEMPERATURE = 0.0

TOP_K = 6
SIMILARITY_THRESHOLD = 0.50

BATCH_SIZE = 32

ENABLE_HYBRID_SEARCH = True
SEMANTIC_WEIGHT = 0.7
KEYWORD_WEIGHT = 0.3
ENABLE_QUERY_EXPANSION = True
MAX_EXPANDED_QUERIES = 3